# Generated by Django 5.1.6 on 2025-02-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Paper', 'Paper'), ('Digital', 'Digital')], default='Paper', max_length=7),
        ),
    ]
