# Generated by Django 5.1.6 on 2025-02-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Paper', 'PAPER'), ('Digital', 'DIGITAL')], default='Paper', max_length=7),
        ),
    ]
